### ISSUE TITLE
Fixed arity functions

### ISSUE THREAD

**Issue by vihanb** [ETHproductions/japt#19]
[tag:feature-request]
Fixed-arity functions will omit the need for lots of spaces and could help golf a _lot_ of bytes

**Comment by ETHproductions** [comment]
I was just thinking about this the other day. I'll need to rearrange some functions so as to make this more efficient. Hopefully this will be a feature in Japt 2.0.

**Comment by ETHproductions** [comment]
With the introduction of more shortcuts and a clearer plan for Japt 2, this has become somewhat irrelevant.

Japt 2 will have some 0-arity methods (somewhat similar to today's shortcuts), but having methods with a maximum arity of 1, 2, etc. introduces ambiguity as to order of operations. If `a` is a method with a fixed arity of 1, then what would `XaYaZ` become? If it's `X.a(Y).a(Z)`, that means you'd have to add a `(` and a space in order to force it to go the other way. If it's `X.a(Y.a(Z))`, you'd have to add a space to switch it, which is exactly the situation we're in now.

Hence, I don't think it's really possible/useful anymore to have methods with fixed arity other than 0.
